<form id="country-city-form" action="<?php echo $this->url(array(), 'home'); ?>" method="POST">
    <div id="country-elements-wrapper">
        <?php if(!empty($this->countries)): ?>
            <?php echo $this->partial('form/country/select.phtml', array('countries' => $this->countries)); ?>
        <?php endif; ?>
    </div>
    <div id="city-elements-wrapper">
        <?php if(!empty($this->cities)): ?>
            <?php echo $this->partial('form/city/select.phtml', array('cities' => $this->cities)); ?>
        <?php endif; ?>        
    </div>
</form>
<script type="text/javascript"> 
    $(document).ready(function() { 
        
        // Pierwszy raz po zaladowaniu strony
        application.onCountrySelectSelect();
        
        $(document).on('click', '#country-city-form input[type=submit]', {}, application.onCityWeatherButtonClick);
        $(document).on('change', '#country-city-form select[name=country]', {}, application.onCountrySelectSelect);
        
//        $(document).on('click', '#country-city-form select[name=country] option:selected', {}, application.onCountrySelectSelect);
//        var $countrySelect = $('select[name=country]');
//        var onSelectedOptionClick = $.proxy(application.onCountrySelectSelect, $countrySelect);
//        $('select[name=country] option:selected').on('click', application.onCountrySelectSelect); 
//        $('input[type=submit]').on('click', application.onCityWeatherButtonClick);
    }); 
</script> 