<form id="country-city-form" action="<?php echo $this->url(array(), 'home'); ?>" method="POST">
    <div id="country-elements-wrapper">
        <?php if(!empty($this->countries)): ?>
            <?php echo $this->partial('form/country/select.phtml', array('countries' => $this->countries)); ?>
        <?php endif; ?>
    </div>
    <div id="city-elements-wrapper">
        <?php if(!empty($this->cities)): ?>
            <?php echo $this->partial('form/city/select.phtml', array('cities' => $this->cities)); ?>
        <?php endif; ?>        
    </div>
</form>
<script type="text/javascript"> 
    $(document).ready(function() { 
//        var $countrySelect = $('select[name=country]');
//        var onSelectedOptionClick = $.proxy(application.onCountrySelectSelect, $countrySelect);
        $('select[name=country] option:selected').live('click', application.onCountrySelectSelect); 
        $('select[name=country]').change(application.onCountrySelectSelect);
        $('input[type=submit]').live('click', application.onCityWeatherButtonClick);
    }); 
</script> 