<div class="pagination">
    <div style="float:left;width:28%"></div>
    <div style="float:right;width:70%;">
        <?php $url = $this->url(array(
                        'controller' => 'order',
                        'action' => 'list',
                        'page' => $this->first
                    ), 'order_list') . $this->sortQuery; ?>
        <!-- First page link -->
        <?php if (isset($this->previous)): ?>
              <a href="<?php echo $this->url(array(
                        'controller' => 'order',
                        'action' => 'list',
                        'page' => $this->first
                    ), 'order_list') . $this->sortQuery; ?>">Start</a> |
        <?php else: ?>
                <span class="disabled">Start</span> |
        <?php endif; ?>
    
        <!-- Poprzednia page link -->
    
        <?php if (isset($this->previous)): ?>
              <a href="<?php echo $this->url(array(
                        'controller' => 'order',
                        'action' => 'list',
                        'page' => $this->previous
                    ), 'order_list') . $this->sortQuery; ?>">&lt; Poprzednia</a> |
        <?php else: ?>
            <span class="disabled">&lt; Poprzednia</span> |
        <?php endif; ?>
        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
                <a href="<?php echo $this->url(array(
                        'controller' => 'order',
                        'action' => 'list',
                        'page' => $page
                    ), 'order_list') . $this->sortQuery; ?>"><?php echo $page; ?></a>
            <?php else: ?>
                <?php echo $page; ?>
            <?php endif; ?>
        <?php endforeach; ?>
        <!-- Następna page link -->
        <?php if (isset($this->next)): ?>
              | <a href="<?php echo $this->url(array(
                        'controller' => 'order',
                        'action' => 'list',
                        'page' => $this->next
                    ), 'order_list') . $this->sortQuery; ?>">Następna &gt;</a> |
        <?php else: ?>
            | <span class="disabled">Następna &gt;</span> |
        <?php endif; ?>
        <!-- Last page link -->
        <?php if (isset($this->next)): ?>
              <a href="<?php echo $this->url(array(
                        'controller' => 'order',
                        'action' => 'list',
                        'page' => $this->last
                    ), 'order_list') . $this->sortQuery; ?>">Koniec</a>
        <?php else: ?>
            <span class="disabled">Koniec</span>
        <?php endif; ?>
        &nbsp; Strona <?php echo $this->current; ?> z <?php echo $this->last; ?>
    </div>
    <div class="clearfix"></div>
 </div>