<?php echo $this->doctype(); ?>

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pl" lang="pl">
    <head>
        <?php echo $this->headTitle($this->title); ?>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headScript(); ?>
        <script type="text/javascript">
            var baseURL = "<?php echo $this->baseUrl(); ?>"
        </script>
    </head>
    <body>
        <section id="wrapper">
            <header id="header">
                <div class="top">
                     <!-- block navigation -->
                        <nav>
                            <ul class="navigation">
                                <li><a href="<?php echo $this->url(array(), 'home'); ?>">Home</a></li>
                                <li><a href="<?php echo $this->url(array(), 'admin_index'); ?>">Admin</a></li>
                            </ul>
                        </nav>
                    <!-- endblock -->
                </div>

                <hgroup>
                    <h2><a href="<?php echo $this->url(array(), 'home'); ?>">Weather Info</a></h2>
                    <h3><a href="#">Aplikacja testowa</a></h3>
                </hgroup>
            </header>
            
            <?php echo $this->layout()->content; ?>
            
            <div id="footer">
                <?php echo $this->layout()->footer; ?>
            </div>
        </section>
    </body>
</html>


