<?php /*<div class="weather">
    <?php if(!empty($this->weather)): ?>
        <?php if(is_string($this->weather)): ?>
            <?php echo $this->weather; ?>
        <?php else: ?>
            <?php echo $this->partial('weather/info.phtml', array('weather' => $this->weather)); ?>
        <?php endif; ?>
    <?php endif; ?>
</div>
 */ ?>
<?php echo $this->weather; ?>
<br />
<span style="font-size: 12px; color: gray">
    <?php echo $this->sourceInformation; ?>
</span>

