<section class="main-col">
    <div id="view-content">
        <div class="flash-messages">
            <?php echo $this->partial('flashmessager.phtml'); ?>
        </div>
        <div class="weather">
            <?php if(!empty($this->weather)): ?>
                <?php echo $this->partial('weather/info.phtml', array('weather' => $this->weather)); ?>
            <?php endif; ?>
        </div>
    </div>
</section>
<aside class="sidebar">
    <?php echo $this->partial('form/side.phtml', array('cities' => $this->cities, 'countries' => $this->countries)); ?>
</aside>